2025-04-23 10:46:08,440 - INFO - ðŸš€ Starting training pipeline
2025-04-23 10:46:08,441 - INFO - Initializing CUDA...
2025-04-23 10:46:08,535 - INFO - CUDA initialized in 0.09s
2025-04-23 10:46:08,536 - INFO - Using GPU: NVIDIA GeForce GTX 1050 Ti
2025-04-23 10:46:08,536 - INFO - Setting up data transformations...
2025-04-23 10:46:08,537 - INFO - Loading datasets from ./train and ./val...
2025-04-23 10:46:08,786 - INFO - Training set loaded with 43444 images
2025-04-23 10:46:08,787 - INFO - Validation set loaded with 8688 images
2025-04-23 10:46:08,787 - INFO - Test set loaded with 2173 images
2025-04-23 10:46:08,788 - INFO - Final splits - Train: 43444, Val: 8688, Test: 2173
2025-04-23 10:46:08,790 - INFO - 
Found 38 classes:
['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy']

2025-04-23 10:46:08,791 - ERROR - ðŸ”¥ Critical error in training pipeline
Traceback (most recent call last):
  File "C:\plant_village\train_cnn_new.py", line 396, in run
    self.setup_data()
  File "C:\plant_village\train_cnn_new.py", line 155, in setup_data
    self._log_class_distribution(train_data, val_data, test_data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PlantDiseaseTrainer' object has no attribute '_log_class_distribution'
